# Generated by Django 4.0.6 on 2022-08-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move', '0002_movedetail_previous_quant_alter_move_date_move_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='date_today',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
